# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Server BridgeTests' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Server Bridge

  target 'Server Bridge' do
    inherit! :search_paths
    pod 'SwiftSocket'
    pod 'Socket.IO-Client-Swift', '~> 13.3.0'
  end

end
